### PR TITLE
Immutable read

### PR DESCRIPTION
**Pull request by kayceesrk**
**DO NOT MERGE**

### CODE REVIEW

**Comment by lpw25** [comment]
I see that you're using the immutable read annotations for more than the read barrier. Since I don't know precisely what property you require. I should point out that the notion of "immutable" in this patch means, corresponds to a read being immutable from the language's point of view. This guarantees:

1. If you read from it twice it will return the same value
2. The result of a read will not be affected by mutable write operations

However, it does not mean that there won't be "initialising writes" that affect the value being read (e.g. a recursively defined immutable record). It's important to be clear on this as some optimisations require the stronger property that no writes at all can affect the value read. In fact my current plan is to use a type like:

```
type read =
  | Pure
  | Immutable
  | Mutable
```

where `Pure` is for values (e.g. modules) which are never affected by initialising or mutating writes, whilst `Immutable` is for those which are not affected by mutating writes, but could be subject to initialising writes. In particular, I think on `trunk` there is a mutability flag on `Iload` and I believe that corresponds to `Pure` rather than `Immutable` for the purposes of instruction scheduling.

**Comment by stedolan** [comment]
For these purposes, I think the notion of "immutable" we need is "all writes happen-before all reads", with happens-before defined by the memory model (and including program order).

By the way, I'm not convinced that `Pure` values exist in OCaml. Recursive modules mean that initialising writes can happen even to module fields.

**Comment by lpw25** [comment]
> Recursive modules mean that initialising writes can happen even to module fields.

Actually, I don't think they can. IIUC the compilation scheme for recursive modules actually allocates both the module block and the blocks for the fields initially and then mutates the blocks for the fields rather than mutating the module block.

**Comment by kayceesrk** [comment]
Closing old PRs.

**Pull request closed without merging**
